actions:
  pre:
    vim-plug-install: test -e ~/.config/nvim/autoload/plug.vim || (mkdir -p ~/.config/nvim/autoload;
      curl -fLo ~/.config/nvim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim)
  vim-plug: nvim +PlugInstall +qall
config:
  backup: false
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: link
  link_on_import: link
  longkey: false
  showdiff: true
  workdir: ~/.config/dotdrop
dotfiles:
  f_wallpaper:
    dst: ~/wallpapers/wallpaper.png
    src: wallpapers/wallpaper.png
  f_alacritty.yml:
    dst: ~/.config/alacritty/alacritty.yml
    src: config/alacritty/alacritty.yml
  f_i3config:
    dst: ~/.config/i3/config
    src: config/i3/config
  f_fehbg:
    dst: ~/.fehbg
    src: fehbg
  f_init.vim:
    actions:
    - vim-plug-install
    - vim-plug
    dst: ~/.config/nvim/init.vim
    src: config/nvim/init.vim
  f_launch.sh:
    dst: ~/.config/polybar/launch.sh
    src: config/polybar/launch.sh
  f_pam_environment:
    dst: ~/.pam_environment
    src: pam_environment
  f_polybar_config:
    dst: ~/.config/polybar/config
    src: config/polybar/config
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
  f_config.rasi:
    src: config/rofi/config.rasi
    dst: ~/.config/rofi/config.rasi
  d_autorandr:
    src: config/autorandr
    dst: ~/.config/autorandr
profiles:
  stroggii:
    dotfiles:
    - ALL
    variables:
      has_gaps: true
      has_polybar: true
      hidpi: true
      kblayout: us
  x230:
    dotfiles:
    - ALL
    variables:
      has_gaps: true
      has_polybar: true
  precision7540:
    dotfiles:
    - f_alacritty.yml
    - f_config.rasi
    - f_fehbg
    - f_i3config
    - f_init.vim
    - f_wallpaper
    - d_autorandr
    variables:
      kblayout: jp
variables:
  kblayout: gb
