actions:
  pre:
    vim-plug-install: test -e ~/.config/nvim/autoload/plug.vim || (mkdir -p ~/.config/nvim/autoload; curl
      -fLo ~/.config/nvim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim)
  vim-plug: nvim +PlugInstall +qall
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_by_default: false
  link_dotfile_default: nolink
  link_import_default: nolink
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  f_init.vim:
    dst: ~/.config/nvim/init.vim
    src: config/nvim/init.vim
    actions:
      - vim-plug-install
      - vim-plug
profiles:
  stroggii:
    dotfiles:
    - ALL
  x230:
    dotfiles:
    - ALL
