actions:
  pre:
    vim-plug-install: test -e ~/.config/nvim/autoload/plug.vim || (mkdir -p ~/.config/nvim/autoload;
      curl -fLo ~/.config/nvim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim)
  vim-plug: nvim +PlugInstall +qall
config:
  backup: false
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_by_default: false
  link_dotfile_default: nolink
  link_import_default: nolink
  longkey: false
  showdiff: true
  workdir: ~/.config/dotdrop
dotfiles:
  f_a_night_to_come_back.png:
    dst: ~/wallpapers/a_night_to_come_back.png
    src: wallpapers/a_night_to_come_back.png
  f_alacritty.yml:
    dst: ~/.config/alacritty/alacritty.yml
    src: config/alacritty/alacritty.yml
  f_config:
    dst: ~/.config/i3/config
    src: config/i3/config
  f_fehbg:
    dst: ~/.fehbg
    src: fehbg
  f_init.vim:
    actions:
    - vim-plug-install
    - vim-plug
    dst: ~/.config/nvim/init.vim
    src: config/nvim/init.vim
  f_launch.sh:
    dst: ~/.config/polybar/launch.sh
    src: config/polybar/launch.sh
  f_pam_environment:
    dst: ~/.pam_environment
    src: pam_environment
  f_polybar_config:
    dst: ~/.config/polybar/config
    src: config/polybar/config
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
profiles:
  stroggii:
    dotfiles:
    - ALL
    variables:
      hidpi: true
      kblayout: us
  x230:
    dotfiles:
    - ALL
variables:
  kblayout: gb
